// <auto-generated />
using System.Collections.Generic;
using Infrastructure.Reference;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Reference.Migrations
{
    [DbContext(typeof(ReferenceDbContext))]
    [Migration("20251114142850_Init Reference Db")]
    partial class InitReferenceDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Reference.Entities.AdditionalReference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyExpenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("MonthlyExpenses");

                    b.Property<decimal>("SeamstressAverageSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("SeamstressAverageSalary");

                    b.Property<int>("SeamstressCount")
                        .HasColumnType("integer")
                        .HasColumnName("SeamstressCount");

                    b.ComplexProperty<Dictionary<string, object>>("Factors", "Domain.Reference.Entities.AdditionalReference.Factors#LaborOverheadFactors", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Cutting")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("CuttingFactor");

                            b1.Property<decimal>("Master")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("MasterFactor");

                            b1.Property<decimal>("SeamstressBonus")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("SeamstressBonusFactor");

                            b1.Property<decimal>("WorkshopManager")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("WorkshopManagerFactor");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PpeProfit", "Domain.Reference.Entities.AdditionalReference.PpeProfit#ProfitFactors", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Above40Units")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("PpeAbove40UnitsProfit");

                            b1.Property<decimal>("TenTo40Units")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("PpeTenTo40UnitsProfit");

                            b1.Property<decimal>("UpTo10Units")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("PpeUpTo10UnitsProfit");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ProducedProfit", "Domain.Reference.Entities.AdditionalReference.ProducedProfit#ProfitFactors", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Above40Units")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("ProducedAbove40UnitsProfit");

                            b1.Property<decimal>("TenTo40Units")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("ProducedTenTo40UnitsProfit");

                            b1.Property<decimal>("UpTo10Units")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("ProducedUpTo10UnitsProfit");
                        });

                    b.HasKey("Id");

                    b.ToTable("AdditionalReferences", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
